name: check_py

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ruff:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: rustup update

      - uses: astral-sh/setup-uv@v6
        with:
          python-version: "3.9"

      - run: |
          uv pip install ruff

      - run: |
          uv ruff check
          uv ruff format --check --diff

  staticcheck:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: rustup update

      - uses: astral-sh/setup-uv@v6
        with:
          python-version: "3.9"

      - run: |
          # Require -e to pass pyright checks
          uv pip install -e .[dev]

      - name: Run mypy
        run: |
          uv run mypy

      - name: Run pyright
        run: |
          uv run pyright
