name: test_py

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pytest:
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]
        python: ["3.9", "3.10", "3.11", "3.12", "3.13", "3.13t"]

    name: "py${{ matrix.python }}_${{ matrix.os }}"
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - run: rustup update

      - uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python }}

      - name: Run Python tests
        run: |
          # Test with minimal dependencies
          uv sync
          uv pip install pytest tomli
          uv run pytest
